### ISSUE TITLE
dtls timed out

### ISSUE THREAD

**Issue by raqbit** [eriklupander/tradfri-go#3] opened 2019-05-18 14:27 UTC
I'm able to use `tradfri-go --authenticate` to authenticate to the gateway and the `config.json` file has been created. 
But, when trying to start the server I get this error after a couple of seconds:

```
Running in server mode on :8080
Connecting to peer at <ip:port>
Unable to connect to Gateway at <ip:port>: dtls: timed out waiting for handshake to complete
```
I'm getting the same error with https://github.com/barnybug/go-tradfri, so the error might be related to the shared dlts library.

Do you know what might cause this?

**Comment by eriklupander** [comment] 2019-06-08 12:11
Hi, sorry for not getting back earlier.

It's hard to say, seems a bit weird if you can authenticate and get a key back (written to the json file), but not complete the handshake when subsequently trying to connect with your new key.

Sorry I can't be of more help.

**Comment by Age15990** [comment] 2019-06-15 17:58
Hi,

I had the same issue today. Had the server running and authorized on one machine and then authorized with a different client id on another machine. The server on the second machine always responded with a 500 and dtls timed out.
After letting the second server run with the config file from server one, everything was fine.

Did not dig into this one yet, but maybe multiple keys cause this issue?

**Comment by eriklupander** [comment] 2019-06-16 08:24
Hi,

I've seen that one can only perform the key exchange once per client-id, but I don't think my gateway has an issue using an "old" client-id after performing an exchange for another client-id.

Wouldn't make sense since I think each device you want to use with your Tradfri things (different phones, tablets etc) probably uses a unique generated client-id.

I don't have access to my Tradfri stuff at the moment, but will try to reproduce your issue once I have.

Thanks for letting me know about your issue!

**Comment by Age15990** [comment] 2019-06-17 07:23
Hi,

bit off topic, but I would love to add grpc support for your project. I have been working on that yesterday and hope to finish it this week. Is that something you are interested in?
I am working on some webhooks for my smart home integration and would really like my own API being REST and all the integrations working via grpc.

Greetings,
Ann-Katrin

**Comment by eriklupander** [comment] 2019-06-17 15:42
> Hi,
> 
> bit off topic, but I would love to add grpc support for your project. I have been working on that yesterday and hope to finish it this week. Is that something you are interested in?
> I am working on some webhooks for my smart home integration and would really like my own API being REST and all the integrations working via grpc.
> 
> Greetings,
> Ann-Katrin

Hi, grpc support sounds great. Feel free to submit a Pull Request once you're ready. Much appreciated! 

// Erik

**Comment by eriklupander** [comment] 2020-10-11 09:46
Closing this issue since it's really old.

**Closed as completed by eriklupander** 2020-10-11 09:46 UTC
